import os
import subprocess
from datetime import datetime
from typing import Dict, List

from .config import Settings

CATEGORY_LABELS = {
    "safe": "🟢 Safe",
    "review": "🟡 Review",
    "personal": "🔵 Personal",
}


def scan(settings: Settings) -> List[Dict[str, str]]:
    targets = _build_targets(settings)
    items = []
    for target in targets:
        path = os.path.expanduser(target["path"])
        if target.get("resolve") == "brew":
            path = _brew_cache_path()
        if not path or not os.path.exists(path):
            continue
        size = _get_size_bytes(path)
        metadata = {
            **target,
            "path": path,
            "size_bytes": size,
            "size_human": _format_bytes(size),
            "category_label": CATEGORY_LABELS.get(target["category"], target["category"]),
        }
        if target.get("include_age"):
            metadata.update(_age_metadata(path))
        if target.get("include_dates"):
            metadata.update(_backup_dates(path))
        items.append(metadata)
    items.extend(_find_orphaned_app_support())
    return items


def _build_targets(settings: Settings) -> List[Dict[str, str]]:
    base = [
        {
            "name": "macOS Caches",
            "path": "~/Library/Caches",
            "category": "safe",
            "default_explanation": "Cache files can be regenerated by apps.",
            "default_consequence": "Apps may take slightly longer to rebuild caches.",
        },
        {
            "name": "macOS Logs",
            "path": "~/Library/Logs",
            "category": "safe",
            "default_explanation": "Log files can be regenerated by the system.",
            "default_consequence": "Old logs will be removed.",
        },
        {
            "name": "Xcode DerivedData",
            "path": "~/Library/Developer/Xcode/DerivedData",
            "category": "safe",
            "default_explanation": "Xcode rebuilds DerivedData on demand.",
            "default_consequence": "Xcode rebuild times increase temporarily.",
        },
        {
            "name": "Homebrew Cache",
            "path": "",
            "resolve": "brew",
            "category": "safe",
            "default_explanation": "Homebrew can re-download cached bottles.",
            "default_consequence": "Homebrew will re-download packages when needed.",
        },
        {
            "name": "npm Cache",
            "path": "~/.npm/_cacache",
            "category": "safe",
            "default_explanation": "npm can rebuild package caches.",
            "default_consequence": "npm may download packages again.",
        },
        {
            "name": "pip Cache",
            "path": "~/Library/Caches/pip",
            "category": "safe",
            "default_explanation": "pip can re-download cached wheels.",
            "default_consequence": "pip may download packages again.",
        },
        {
            "name": "Cargo Cache",
            "path": "~/.cargo/registry/cache",
            "category": "safe",
            "default_explanation": "Cargo can re-download registry artifacts.",
            "default_consequence": "cargo may download crates again.",
        },
        {
            "name": "iOS Simulators",
            "path": "~/Library/Developer/CoreSimulator",
            "category": "review",
            "default_explanation": "Simulator runtimes can be reinstalled.",
            "default_consequence": "You may need to re-download simulator runtimes.",
        },
        {
            "name": "iOS Backups",
            "path": "~/Library/Application Support/MobileSync/Backup",
            "category": "review",
            "default_explanation": "Old device backups can be removed.",
            "default_consequence": "You lose the ability to restore from those backups.",
            "include_dates": True,
        },
        {
            "name": "Downloads",
            "path": "~/Downloads",
            "category": "personal",
            "default_explanation": "Personal downloads may be important.",
            "default_consequence": "Files are permanently removed if deleted.",
            "include_age": True,
        },
        {
            "name": "Trash",
            "path": "~/.Trash",
            "category": "personal",
            "default_explanation": "These files are already in Trash.",
            "default_consequence": "Trash will be emptied.",
        },
    ]
    if settings.scan_locations:
        for name, path in settings.scan_locations.items():
            base.append(
                {
                    "name": name,
                    "path": path,
                    "category": "review",
                    "default_explanation": "Custom location.",
                    "default_consequence": "Files will be removed.",
                }
            )
    return base


def _get_size_bytes(path: str) -> int:
    if os.path.isfile(path):
        return os.path.getsize(path)
    total = 0
    for root, _, files in os.walk(path):
        for name in files:
            try:
                total += os.path.getsize(os.path.join(root, name))
            except OSError:
                continue
    return total


def _format_bytes(size: int) -> str:
    units = ["B", "KB", "MB", "GB", "TB"]
    value = float(size)
    for unit in units:
        if value < 1024 or unit == units[-1]:
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{value:.1f} TB"


def _brew_cache_path() -> str:
    try:
        result = subprocess.run(["brew", "--cache"], capture_output=True, text=True, check=True)
        return result.stdout.strip()
    except (subprocess.SubprocessError, FileNotFoundError):
        return ""


def _age_metadata(path: str) -> Dict[str, str]:
    timestamps = []
    for root, _, files in os.walk(path):
        for name in files:
            try:
                timestamps.append(os.path.getmtime(os.path.join(root, name)))
            except OSError:
                continue
    if not timestamps:
        return {"age_summary": "No files found."}
    oldest = datetime.fromtimestamp(min(timestamps)).strftime("%Y-%m-%d")
    newest = datetime.fromtimestamp(max(timestamps)).strftime("%Y-%m-%d")
    return {"age_summary": f"Oldest: {oldest}, newest: {newest}"}


def _backup_dates(path: str) -> Dict[str, str]:
    dates = []
    if os.path.isdir(path):
        for name in os.listdir(path):
            full = os.path.join(path, name)
            if os.path.isdir(full):
                dates.append(datetime.fromtimestamp(os.path.getmtime(full)).strftime("%Y-%m-%d"))
    if not dates:
        return {"backup_dates": "No backups detected."}
    return {"backup_dates": ", ".join(sorted(dates)[:5])}


def _find_orphaned_app_support() -> List[Dict[str, str]]:
    support_path = os.path.expanduser("~/Library/Application Support")
    if not os.path.isdir(support_path):
        return []
    app_dirs = {name.lower() for name in os.listdir("/Applications") if name.endswith(".app")}
    items = []
    for name in os.listdir(support_path):
        path = os.path.join(support_path, name)
        if not os.path.isdir(path):
            continue
        if f"{name.lower()}.app" in app_dirs:
            continue
        size = _get_size_bytes(path)
        items.append(
            {
                "name": f"Orphaned support: {name}",
                "path": path,
                "category": "review",
                "default_explanation": "App support folder without a matching installed app.",
                "default_consequence": "App data may be removed if the app is reinstalled.",
                "size_bytes": size,
                "size_human": _format_bytes(size),
                "category_label": CATEGORY_LABELS["review"],
            }
        )
    return items
